import vazirFont from "@/constants/localFont";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="light-mode">
      <body className={`min-h-screen ${vazirFont.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
